(local faith (require :faith))

(faith.run [:app-test
            :action-plan-test
            :args-test
            :git-test
            :git-commands-test
            :git-parse-test
            :messages-test
            :notice-test
            :platform-test
            :review-test
            :search-match-test
            :search-nav-test
            :search-plan-test
            :search-status-test
            :selection-cache-test
            :selection-context-test
            :selection-plan-test
            :preview-test
            :preview-folder-test
            :preview-warm-test
            :preview-warm-plan-test
            :preview-viewport-test
            :preview-workers-test
            :reviews-test
            :sync-test
            :tree-test
            :tui-chrome-layout-test
            :tui-footer-layout-test
            :tui-footer-text-test
            :tui-keys-test
            :tui-test
            :tui-text-highlight-test
            :tui-text-test
            :tui-text-window-test
            :tui-terminal-osc-test
            :tui-terminal-probe-test
            :update-test
            :util-math-test])
